### ISSUE TITLE
Wrongly referring ruby version instead of gem versions

### ISSUE THREAD

**Issue by nobu** [ruby/spec#1046]
```shell-session
$ git grep ruby_version_is library/ | grep -F -v -e /rbconfig/ -e /objectspace/ -e /coverage/ -e /fiber/ | wc -l
192
```

Except for libraries excluded with `grep -v` in the above, the others are default gems and their own versions which are unrelated to `RUBY_VERSION`.

`version_is` must be used with appropriate versions instead of `ruby_version_is`, for example:

```shell-session
$ git grep -w version_is library/
library/bigdecimal/remainder_spec.rb:57:  version_is BigDecimal::VERSION, ""..."3.1.4" do
library/datetime/to_time_spec.rb:22:  version_is(date_version, '3.2.3') do
library/logger/device/close_spec.rb:18:  version_is Logger::VERSION, ""..."1.4.0" do
library/logger/device/close_spec.rb:25:  version_is Logger::VERSION, "1.4.0" do
library/logger/device/write_spec.rb:38:  version_is Logger::VERSION, ""..."1.4.0" do
library/logger/device/write_spec.rb:45:  version_is Logger::VERSION, "1.4.0" do
library/matrix/unitary_spec.rb:17:    version_is((Matrix::const_defined?(:VERSION) ? Matrix::VERSION : "0.1.0"), "0.3.0") do
library/openssl/config/freeze_spec.rb:6:version_is(OpenSSL::VERSION, ""..."2.2") do
library/stringio/initialize_spec.rb:299:    version_is(stringio_version, "0.0.3"..."0.1.1")
library/time/to_datetime_spec.rb:17:  version_is(date_version, '3.2.3') do
```

https://bugs.ruby-lang.org/issues/19762

**Comment by eregon** [comment]
Agreed in general.
Although I think it may be OK to fix specific issues rather than to address the 192 cases when probably most of them work fine in practice.
IIRC some of the default gems did not have a VERSION constant (hopefully not a problem anymore).

> their own versions which are unrelated to `RUBY_VERSION`.

That's not completely true, ruby/spec is meant to be run with the default gems of a Ruby release, and so e.g. default versions are always >= for a newer Ruby release (in version ordering).

**Comment by nobu** [comment]
- Many of the 192 cases are because of the promotion to default gems (matrix, net-ftp, prime).
- io-wait guards are because of Ruby's API addtions.
- socket is not gemified, and should be excluded from the list.

**Comment by nobu** [comment]
As for set/pretty_print_spec.rb (and set/pretty_print_cycle_spec.rb), should not test internal methods, I think.

**Comment by k0kubun** [comment]
> Many of the 192 cases are because of the promotion to default gems (matrix, net-ftp, prime).

Off topic: If many of the default gem specs exist because we wrote them when it was not a gem, would it make sense to migrate such tests to the gem repository (and possibly hook the tests from the ruby/spec suite)? 

Currently, ruby/spec is not executed in default gem repositories, and changes in such repositories often result in ruby/spec failures in ruby/ruby even if the gem's CI is passing (because it doesn't run ruby/spec). Unlike `test-all`, since other Ruby implementations can easily run the tests of gems, it seems redundant to have two different test suites once gemified.

**Comment by eregon** [comment]
Yes,we should probably move the specs of extracted stdlibs to their repo. I think it's a lot of work though. And it would need `mspec` releases (currently there is no compatibility needed in mspec), and we don't own the `mspec` gem (could be `ruby-mspec`).

**Comment by k0kubun** [comment]
> Yes,we should probably move the specs of extracted stdlibs to their repo. 

😍 

> I think it's a lot of work though.

I can migrate ERB as a starter and encourage other active folks to follow it. It never ends unless we start it 🙂 

> we don't own the `mspec` gem

I wonder if @brixen is open to adding you as a gem owner?

> could be `ruby-mspec`

Agreed.
