### ISSUE TITLE
Checks for exact values in core/random/bytes

### ISSUE THREAD

**Issue by herwinw** [ruby/spec#1051]
The spec [core/random/bytes](https://github.com/ruby/spec/blob/master/core/random/bytes_spec.rb) has a few checks for the exact results:
```ruby
  # Should double check this is official spec
  it "returns the same numeric output for a given seed across all implementations and platforms" do
    rnd = Random.new(33)
    rnd.bytes(2).should == "\x14\\"
    rnd.bytes(1000) # skip some
    rnd.bytes(2).should == "\xA1p"
  end
```

The documentation of [Random](https://ruby-doc.org/core-3.1.0/Random.html) contains the following line:
> PRNGs are currently implemented as a modified Mersenne Twister with a period of 2**19937-1.

Although it is described as being modified, I can't find any documentation on how it is modified without digging into the Ruby source code. In Natalie, we tried this using [`std::mt19937`](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine). This results in different output and fails the test (see https://github.com/natalie-lang/natalie/issues/919)

Given that there already is a comment about whether this is the official spec, and there is no official documentation on how the MRI implementation actually works except for the code itself, I'm not sure this check should be in the spec.

**Comment by eregon** [comment]
It is intentional to test the exact values for Random, e.g. also see https://github.com/ruby/spec/blob/1c0ea5c56764290fd67a7b1c9cfe01c4415e4386/core/random/rand_spec.rb#L208-L211
Because it is very valuable when running some Ruby app on another Ruby to actually have the same Random values when given the same seed (e.g. via `srand`).
I'll just remove that comment.
