### ISSUE TITLE
Ripper specs

### ISSUE THREAD

**Issue by mjago** [ruby/spec#455]
There are several good Ripper unit tests in test/ but no ripper specs at all.

1) Is Ripper a thing outside of MRI?
2) Is it worth porting the tests to specs?

I've quite taken to Ripper since I've been helping test the [Rufo](https://github.com/asterite/rufo) project and appreciate the fact that it has zero dependencies and is fast. Rufo formats the entirety of Ruby Specs quite happily by the way! Possibly add to CI eventually?

**Comment by eregon** [comment]
1. It is supported on JRuby at least, so it's not MRI-specific.
2. I am not sure. If it is the exact same tests, it has little value if other implementations can run these Ripper tests (it's not always easy or practical but it's possible). JRuby seems to run [a few of them](https://github.com/jruby/jruby/blob/f3ec650f7059e6fd7bed3f2f049fc39647b034bc/test/mri.index#L330-L334). In some cases it's interesting to port the tests because they are not fine-grained, or it is more complicated to tag failures with MRI tests. But Ripper tests seem fine-grained and duplicating the maintenance effort also has to be considered.

That said, new Ripper specs are welcome, especially if they extend the coverage of what is being tested in Ripper.

From a quick look, Rufo seems nice indeed.
We would have to configure it to be rather flexible, in the same spirit as #444.
While we could add it in this CI, we cannot easily do that for other repos where ruby/spec is synchronized (MRI, JRuby, TruffleRuby). So it has to be very easy to run it when bringing specs from these repos.
If it modifies too much then we increase the chance of conflicts and makes it harder to go through git history.

**Comment by eregon** [comment]
I ran it on the whole suite and it tooks 7s, that's nice.
After running it once, it seems to show it still formats files even though nothing is changed:
```
Error: ./command_line/fixtures/bad_syntax.rb has syntax errors
Error: ./library/bigdecimal/exponent_spec.rb has syntax errors
Format: ./core/array/pack/b_spec.rb
Format: ./core/regexp/shared/quote.rb
Format: ./core/string/fixtures/iso-8859-9-encoding.rb
Format: ./core/io/readpartial_spec.rb
zsh: exit 1     rufo .
```
Would that be a Rufo bug?
It also happens with just `rufo ./core/array/pack/b_spec.rb`.

**Comment by mjago** [comment]
Actually I know about these and are due to investigate. Rufo does report syntax errors where it finds them (presumably bad_syntax.rb is bad syntax). exponent_spec.rb suggests a Ripper bug (Rufo has already found two) - but I need to check.
 
The reformats are almost certainly whitespace-related (Rufo uses Rippers Lexer and Parser in combination to determine comment alignment for instance - if enabled). I'm guessing there are a few more tweaks to be made or an disabled by default option is still causing the Format: report. 

The specs have been a very good source of gnarly edge-cases for testing the formatter 😉.

Yes re. CI I agree with your comments - perhaps ultimately a friendly warning here or a manual check process. Its main purpose is for editor integration - although there is a CI option as well.

I'll take a better look at the Ripper tests and assess the usefulness of specs.

Thanks and closing this issue for now.
