### ISSUE TITLE
Document shared specs

### ISSUE THREAD

**Issue by eregon** [ruby/spec#575]
Shared specs are a key tool to avoid duplication in ruby/spec.
But they are a bit tricky to use.
They should be documented in `CONTRIBUTING.md`.

**Comment by cadwallion** [comment]
I've started in on documentation for shared specs, but due to their complexity it's getting a bit long.  I'm wondering if perhaps instead of having everything in `CONTRIBUTING.md`, it may make sense to move the Guards and Shared Specs into separate docs and link them in the `CONTRIBUTING.md` . They could either live in a `docs/` directory or in the Wiki itself.

I'm happy to keep it all in `CONTRIBUTING.md` or handle splitting it out, just let me know so I can PR appropriately.

**Comment by eregon** [comment]
For convenience, I think it's better to use a file in the repo than the Wiki.

I think `CONTRIBUTING.md` would be the most obvious place to look for this.
Maybe we can refine based on the PR, but I think it would be best to have the most important documentation to write specs in one place.

**Comment by eregon** [comment]
@cadwallion Could you show me what you have currently? :smiley:

**Comment by cadwallion** [comment]
Woops, that'd be helpful if I actually submit what I wrote. :) . #582 added.

**Comment by eregon** [comment]
Fixed by #582, thanks @cadwallion!
