### ISSUE TITLE
Trunk failures

### ISSUE THREAD

**Issue by MSP-Greg** [ruby/spec#606]
@eregon

In ruby-loco (trunk testing), `make spec` has always passed.  Running `mspec` intermittently has errors, but no failures.

I have noticed the issue here with trunk.  It might take a few days, but I'll do some local testing to see what the issue is.  As I recall, in the past it was stable...

Thanks again for your work, Greg

**Comment by eregon** [comment]
Thank you for the report, I didn't notice.
Indeed:
https://ci.appveyor.com/project/eregon/spec-x948i/build/1323/job/cl4g9j1ejwpddswf seems stuck
https://ci.appveyor.com/project/eregon/spec-x948i/build/1322/job/ug1ae6galunaa8g5 SEGV
https://ci.appveyor.com/project/eregon/spec-x948i/build/1320/job/yq2g9lwnd4bro5ik SEGV

The SEGV shows
```
C:/projects/spec-x948i/core/kernel/fixtures/classes.rb:416: [BUG] Segmentation fault
41ruby 2.6.0dev (2018-06-13 trunk 63649) [x64-mingw32]
```
which is from
```ruby
    def f1(s, n)
      warn(s, uplevel: n)
    end
```

I fixed a bug related to that on `trunk`: https://bugs.ruby-lang.org/projects/ruby-trunk/repository/revisions/63650/diff
Maybe newer builds work fine?
Otherwise I would of course appreciate your help since I don't have a Windows development environment.

**Comment by eregon** [comment]
More details about uplevel on https://bugs.ruby-lang.org/issues/14846

**Comment by eregon** [comment]
The [latest build](https://ci.appveyor.com/project/eregon/spec-x948i/build/1325/job/30lw9dtoey511nrr) passes so I guess my patch to MRI fixed it :)
Please reopen if you observe problems again.

**Comment by MSP-Greg** [comment]
Yes, I just saw that.  FYI, the link to my results page is:
https://msp-greg.github.io/file.mingw_test-all.html#test-spec-Failure-Error-Summary.  Runs three times a day, but I have to update the results page manually...

Thanks, Greg

**Comment by eregon** [comment]
> Running `mspec` intermittently has errors, but no failures.

What do you mean by errors/failures?
failure = crash, error = failed spec?

Or mspec's notion of errors/failures in the summary line? I personally don't differentiate between mspec errors & failures, they are failed specs to me (regardless if they throw an exception or return a wrong value), which need to be fixed.

**Comment by MSP-Greg** [comment]
> Or mspec's notion of errors/failures in the summary line?

Yes.

I don't recall 'crashing' (as in forced exit) ever happening.  I do have code to trap for it though...  `test-all` does 'freeze' from time to time.

**Comment by eregon** [comment]
By crashing I meant SEGV or the spec process to abort in the middle of the specs.
Both are quite rare, although SEGV do happen from time to time.
