### ISSUE TITLE
Ruby exception messages specs

### ISSUE THREAD

**Issue by deepj** [ruby/spec#636]
I've been inspired by the following two issues reported in TruffleRuby's issues

- https://github.com/oracle/truffleruby/issues/1467
- https://github.com/oracle/truffleruby/issues/1522

Any Ruby implementation would follow primarily original MRI exception messages.

**Comment by eregon** [comment]
Hello and thanks for the report.
Chris already added a few specs for the first issue in https://github.com/oracle/truffleruby/commit/9d38715db488638aa5159d13ee4e176b0adedb9e#diff-bbff3c0323709bdf10685c36d74e08ed

Specs for the second issue are welcome, although it seems more of a nice-to-have (reporting all unknown arguments instead of the first one).

**Comment by eregon** [comment]
Let me close this as there is no specific action to do here.
Specs testing exception messages are welcome, they are part of the observable behavior, and it is frequent gems rely on it.
