### ISSUE TITLE
project setup and mspec

### ISSUE THREAD

**Issue by colby-swandale** [ruby/spec#637]
Hi! 👋 

This is a general question rather then an actual problem. Is there a reason why we need to clone the `mspec` repo to run these tests? As a person coming to this project for the first time, this seems to be a fair bit of work to setup. There is an `mspec` gem but there hasn't been a new release since nearly 3 years. Is there an opportunity make the setup process easier by releasing a new version?

My other question, could this be converted to use minitest instead? It ships with ruby and has support for specs so that the descriptions can be retained. This would make running the spec suite very simple for the end users.

Thanks in advance!

**Comment by eregon** [comment]
Hello,

Those are good questions, and relate to https://github.com/ruby/mspec/issues/14.

To get a better idea, what do you want to use `mspec` for?
Is it for running ruby/spec on a Ruby implementation? If so, the synchronized copy under `spec/ruby` and `spec/mspec` should be used (in MRI, JRuby, TruffleRuby, Opal), and there are shortcuts to run specs (e.g., `make test-spec` in MRI). Those are run in CI and this repo is mostly for synchronizing all specs.

The main reason to use latest mspec is then it's possible to have very quick changes in MSpec, e.g. deprecate one method and immediately replace usages in ruby/spec.
One issue is I'm not an owner of the [mspec gem](https://rubygems.org/gems/mspec).

One interesting question from https://github.com/ruby/mspec/issues/14 is:
> Why maintain mspec as a separate repository at all if it is intimately tied to rubyspec?

I have been thinking this could be a way forward. But I'm not sure how it would look like in the folder hierarchy.

> My other question, could this be converted to use minitest instead? It ships with ruby and has support for specs so that the descriptions can be retained. This would make running the spec suite very simple for the end users.

No, because it would be a huge/"nobody would be patient enough" amount of work for little gains IMHO.
minitest/spec is pretty small, and of course does not have all the [mspec guards](https://github.com/ruby/spec/blob/master/CONTRIBUTING.md#guards), such as `platform_is :windows do`, etc.
Using RSpec would have a similar problem: the syntax of RSpec 2 is mostly compatibly, but it has very few of the helpers used here, and e.g. no tagging support which is essential for JRuby, TruffleRuby, etc.

We could likely have a Rakefile or so, so running `ruby/spec` with the `ruby` in `PATH` would just be `git clone`, `cd` and `rake` for instance, would that help?

**Comment by eregon** [comment]
BTW, I was once using `bundle exec` to execute specs in TravisCI, with a `Gemfile` depending on `mspec` by using `path:` (which is a more standard setup), but this turned out to create subtle bugs, add complexity for external process specs, and slow down the execution of all specs quite significantly.

**Comment by colby-swandale** [comment]
Thanks for answering my questions @eregon 👏
