### ISSUE TITLE
Clocks are under-specified

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#665]
The documentation says which clocks `Process::CLOCK_...` constants should be available on which platforms - we could specify that.

The symbol versions of clocks, for example `:GETTIMEOFDAY_BASED_CLOCK_REALTIME` aren't specified at all.

**Comment by eregon** [comment]
This might be a bit tricky as which `CLOCK_` are defined might depend on OS, kernel version, user permissions, etc, see https://github.com/ruby/spec/blob/master/core/process/clock_gettime_spec.rb

But we could certainly spec the common ones that don't have too much of these problems.

> The symbol versions of clocks, for example `:GETTIMEOFDAY_BASED_CLOCK_REALTIME` aren't specified at all.

I'm a bit unsure whether those should actually be considered public API or internals accidentally leaking.
Since they are documented, I guess we should consider them public API (even though I think there are no use cases for using the emulation Symbols directly and one should just use CLOCK_REALTIME/CLOCK_MONOTONIC/CLOCK_PROCESS_CPUTIME_ID).
