### ISSUE TITLE
Linter to check code style

### ISSUE THREAD

**Issue by andrykonchin** [ruby/spec#779]
I am wondering whether it makes sense to automate some code style rules (specific to RubySpec codebase) with linter (e.g. Rubocop)? Even if it requires adding custom rules/cops...

For instance linter could detect:
- declaring new classes/global methods
- using `-> {}.should_not raise_error`
- test name duplication (issue https://github.com/ruby/spec/issues/664)

**Comment by eregon** [comment]
Currently RuboCop for ruby/spec is only run in this repo, not in CRuby, JRuby and TruffleRuby's copy of the specs.
It's kind of intentional, I don't want to bother people with overly strict style there, and it's usually trivial fixes when synchronizing.

I think for these 3 cases it's better in MSpec, in order:
* already implemented (with `CHECK_LEAKS=true`)
* could be a deprecation in MSpec (but need to fix usages in ruby/spec first to avoid many warnings)
* can be easily checked in MSpec (but needs to fix cases in ruby/spec first too)

**Comment by eregon** [comment]
Also, as much as possible, I'd also like to keep ruby/spec free of dependencies besides MSpec, including using such checks.
