### ISSUE TITLE
dynamically require language specs for used ruby version

### ISSUE THREAD

**Issue by iliabylich** [ruby/spec#817]
So basically I'm looking at language specs and all of them use `eval` for new Ruby syntax. Because of that `language` specs can't be easily used to validate parsers/unparsers.

Is there any chance to extract these features into separate files, require them dynamically if `ruby_version_is <supported>` and drop `eval` calls?

**Comment by eregon** [comment]
> Is there any chance to extract these features into separate files, require them dynamically if `ruby_version_is <supported>` and drop `eval` calls?

Not really, because that would make it so much harder to see both the tested code and the expectations/tests on it.
I think that was used a long time ago in 1.8/1.9 and from what I got it was a nightmare to maintain.
I already don't like too much the separation between fixtures and spec files.

However, you might be able to either scan for `eval()` calls and try parsing the given string (if it's a string literal), or redefine `eval` to the original meaning + passing that string to the parser.
Both of these won't really work if the `eval` assumes some local variables are defined in the caller.

Actually, since you have a parser and unparser, you could maybe automatically transform the language specs to replace the `eval("some code")` calls with `"some code"`? That sounds fun and should work for most eval, except those that are expected to raise SyntaxError (which you can probably detect with the parser).

**Comment by iliabylich** [comment]
> Both of these won't really work if the eval assumes some local variables are defined in the caller (e.g., a = 3; eval "a + 2").

Yeah, this should work.

> Actually, since you have a parser and unparser, you could maybe automatically transform the language specs to replace the eval("some code") calls with some code? 

These literals can be dynamic. I didn't check the code, but it's possible. Well, I guess I could just ignore them (they are different str/dstr nodes anyway). Thanks!
