### ISSUE TITLE
Document sync process

### ISSUE THREAD

**Issue by chrisseaton** [ruby/spec#820]
I'm interested in the process you're using to take commits from implementation repos and apply just the parts for specs in a different directory structure here.

Is that documented somewhere?

**Comment by eregon** [comment]
Yes, there is a wiki page about it:
https://github.com/ruby/spec/wiki/Merging-specs-from-JRuby-and-other-sources

Nowadays I use a script to do that work (it also works for ruby/mspec in addition to ruby/spec):
https://github.com/ruby/mspec/blob/master/tool/sync/sync-rubyspec.rb

As more background, I initially used `git subtree` but `git subtree split` at some point broke (couldn't find some commit hash), so I switched to the lower-level `git filter-branch --subdirectory-filter` mentioned above, which is also faster.

**Comment by chrisseaton** [comment]
Thanks I didn't find this because it looks like there is a comprehensive `CONTRIBUTING.md` so I didn't also go looking for the Wiki. Could we reference the wiki from the contributing file, or include the wiki content in the contributing file?

**Comment by eregon** [comment]
That wiki page is not kept up to date anymore (although it's probably pretty close to what the script does), since the script is what is actually used now.

I could add a link to the script in https://github.com/ruby/spec#synchronization-with-ruby-implementations, and potentially link to the wiki in the script in a comment, is that helpful?

**Comment by chrisseaton** [comment]
Sounds good.

**Comment by eregon** [comment]
Done.

**Comment by chrisseaton** [comment]
Cheers.
