### ISSUE TITLE
Dropping support for Ruby 2.5

### ISSUE THREAD

**Issue by eregon** [ruby/spec#835]
So far, ruby/spec has dropped support for a Ruby version soon after it became EOL.
Ruby 2.5 became EOL in https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/

However, current JRuby releases (9.2.x) target Ruby 2.5.
JRuby's master targets Ruby 2.6, though.

Dropping Ruby 2.5 would mean it would be much harder to synchronize specs to & from the 9.2 branch (https://github.com/jruby/jruby/tree/jruby-9.2).
Specs are always synchronized with the `master` branch though, but I think there are merges between `jruby-9.2` and `master`.

@headius @enebo What do you think? Is it OK to drop Ruby 2.5 support in ruby/spec and therefore `jruby-9.2` would have its own non-updated/vendored version of ruby/spec?
Are new specs in JRuby added to master, or sometimes they are added to the 9.2 branch first instead?

**Comment by headius** [comment]
JRuby 9.2 will not be EOL for at least the rest of the year. We will release 9.3 soon (2.6) and 9.4 later this year (3.0) but 9.2 will be in maintenance mode for 6-12 months (undecided, depends on adoption of 9.3 and release of 9.4).

JRuby's jruby-9.2 branch is periodically merged to master. Specs have not been updated there in quite some time.

Specs for things fixed in 9.2 will often go on the 9.2 branch, but there have not been many such fixes recently.

I think that dropping 2.5 specs from ruby/spec just three months after 2.5 EOL is premature. I would vote for keeping them for at least a year.

In any case, I don't think it would affect JRuby's 9.2 branch since we have not been updating specs there and it will be in maintenance mode soon.

Is there a compelling reason to drop 2.5 support from the specs so quickly after EOL?

**Comment by eregon** [comment]
> Is there a compelling reason to drop 2.5 support from the specs so quickly after EOL?

To simplify specs, so there is a smaller range of versions supported, it's a bit easier to maintain, and also to be able to use new features introduced in the minimum version, so in this case to be able to use Ruby 2.6 features in specs (and also in mspec).
As an example, endless Ranges could be nice for `ruby_version_is "2.7"... do`, as people are frequently confused with `ruby_version_is "2.7" do`.
