### ISSUE TITLE
Failures with tzdata-2022b

### ISSUE THREAD

**Issue by voxik** [ruby/spec#936]
With update of tzdata in Fedora from 2022a to 2022b, I started to observe several test failures:

~~~
1)
Time.local timezone changes correctly adjusts the timezone change to 'CEST' on 'Europe/Amsterdam' FAILED
Expected [0, 0, 0, 16, 5, 1940, 4, 137, true, "WEST"] == [0, 40, 1, 16, 5, 1940, 4, 137, true, "CEST"]
to be truthy but was false
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:13:in `block (5 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:12:in `block (4 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/local_spec.rb:5:in `<top (required)>'
2)
Time.mktime timezone changes correctly adjusts the timezone change to 'CEST' on 'Europe/Amsterdam' FAILED
Expected [0, 0, 0, 16, 5, 1940, 4, 137, true, "WEST"] == [0, 40, 1, 16, 5, 1940, 4, 137, true, "CEST"]
to be truthy but was false
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:13:in `block (5 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:12:in `block (4 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/mktime_spec.rb:5:in `<top (required)>'
3)
Time.new timezone changes correctly adjusts the timezone change to 'CEST' on 'Europe/Amsterdam' FAILED
Expected [0, 0, 0, 16, 5, 1940, 4, 137, true, "WEST"] == [0, 40, 1, 16, 5, 1940, 4, 137, true, "CEST"]
to be truthy but was false
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:13:in `block (5 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/shared/local.rb:12:in `block (4 levels) in <top (required)>'
/builddir/build/BUILD/ruby-3.1.2/spec/ruby/core/time/new_spec.rb:11:in `<top (required)>'
Finished in 73.148502 seconds
3817 files, 30898 examples, 133657 expectations, 3 failures, 0 errors, 0 tagged
~~~

Reporting this against [tzdata](https://bugzilla.redhat.com/show_bug.cgi?id=2118259), I was told that this is expected change and the test needs to be fixed. Not sure if the correct change is bumping the year from 1940 => 1970 though, because it seems that 1940 was originally chosen on purpose.

**Comment by eregon** [comment]
Interesting, so `Europe/Amsterdam` in 1940 is not CEST but "WEST"?
Does the test pass by changing to 1970? PR welcome BTW.

> because it seems that 1940 was originally chosen on purpose.

Because of https://github.com/ruby/spec/commit/fb2bf67c3575ec3357dc883cbe6d927930c1a53c ?

Changing the expectation to WEST wouldn't work against older tzdata, so using a different year seems more reliable.

**Comment by junaruga** [comment]
I investigated this issue.

> Because of https://github.com/ruby/spec/commit/fb2bf67c3575ec3357dc883cbe6d927930c1a53c ?

It seems that the commit above added the test cases. But according to [the comment](https://bugzilla.redhat.com/show_bug.cgi?id=2118259#c1) for tzdata RPM package issue ticket on Fedora, and checking the [tzdata project](https://www.iana.org/time-zones), here is the caused commit. This is intentional. The change is new in tzdata version "2022b".

https://github.com/eggert/tz/commit/35fa37fbbb152f5dbed4fd5edfdc968e3584fe12

On ruby/ruby, I found the commit to comment out the tests. My guess is that it is a temporary workaround to pass the tests. And the "2022c" is not accurate. It should be "2022b".

The tzdata 2022c removed Amsterdam Mean Time
https://github.com/ruby/ruby/commit/b7577b4d9e0fd92522fc30e10fe712e245adee8c

> Changing the expectation to WEST wouldn't work against older tzdata, so using a different year seems more reliable.

I would suggest this patch for the ruby/ruby and (ruby/spec).

```
diff --git a/spec/ruby/core/time/shared/local.rb b/spec/ruby/core/time/shared/local.rb
index 997b7186f1..bd33fa01ac 100644
--- a/spec/ruby/core/time/shared/local.rb
+++ b/spec/ruby/core/time/shared/local.rb
@@ -6,18 +6,18 @@
     end
   end
 
-=begin
   platform_is_not :windows do
     describe "timezone changes" do
       it "correctly adjusts the timezone change to 'CEST' on 'Europe/Amsterdam'" do
         with_timezone("Europe/Amsterdam") do
-          Time.send(@method, 1940, 5, 16).to_a.should ==
-            [0, 40, 1, 16, 5, 1940, 4, 137, true, "CEST"]
+          [
+            [0, 40, 1, 16, 5, 1940, 4, 137, true, "CEST"],
+            [0, 0, 0, 16, 5, 1940, 4, 137, true, "WEST"]
+          ].should include(Time.send(@method, 1940, 5, 16).to_a)
         end
       end
     end
   end
-=end
 end
 
 describe :time_local_10_arg, shared: true do
```

**Comment by eregon** [comment]
Could you make a PR with that?

Also would it work to change 1940 by 1970? I think that would be simpler.

**Comment by junaruga** [comment]
Sure. I will send the PR with the 1970.

**Comment by junaruga** [comment]
I sent the PR: https://github.com/ruby/spec/pull/939.
